# config/config.yaml
app:
  name: "security-monitoring"
  version: "0.1.0"
  environment: "${ENVIRONMENT:-development}"
  
database:
  url: "${DATABASE_URL}"
  max_connections: "${DB_MAX_CONNECTIONS:-10}"
  pool_timeout: 30
  
analytics:
  event_buffer_size: "${EVENT_BUFFER_SIZE:-10000}"
  port_scan_threshold: "${PORT_SCAN_THRESHOLD:-50}"
  data_exfiltration_threshold: "${DATA_EXFILTRATION_THRESHOLD:-10485760}"
  suspicious_processes: "${SUSPICIOUS_PROCESSES:-powershell.exe,cmd.exe,wscript.exe,cscript.exe,rundll32.exe,regsvr32.exe}"
  system_metrics_interval: "${SYSTEM_METRICS_INTERVAL:-60}"
  
api:
  graphql_endpoint: "${GRAPHQL_ENDPOINT:-127.0.0.1:8000}"
  cors_origins: "${CORS_ORIGINS:-http://localhost:3000}"
  jwt_secret: "${JWT_SECRET}"
  rate_limit: "${API_RATE_LIMIT:-100}"
  
collaboration:
  websocket_endpoint: "${WEBSOCKET_ENDPOINT:-127.0.0.1:8001}"
  redis_url: "${REDIS_URL}"
  
observability:
  log_level: "${RUST_LOG:-info}"
  jaeger_endpoint: "${JAEGER_ENDPOINT:-localhost:6831}"
  metrics_endpoint: "${METRICS_ENDPOINT:-localhost:9090}"
  enable_tracing: "${ENABLE_TRACING:-false}"
  enable_metrics: "${ENABLE_METRICS:-true}"
  
security:
  tls_cert_path: "${TLS_CERT_PATH}"
  tls_key_path: "${TLS_KEY_PATH}"
  allowed_hosts: "${ALLOWED_HOSTS:-*}"
  
monitoring:
  prometheus_scrape_interval: "${PROMETHEUS_SCRAPE_INTERVAL:-15}"
  alertmanager_url: "${ALERTMANAGER_URL}"
  
deployment:
  health_check_interval: "${HEALTH_CHECK_INTERVAL:-30}"
  graceful_shutdown_timeout: "${GRACEFUL_SHUTDOWN_TIMEOUT:-30}"