# config/development.yaml
app:
  environment: "development"
  
database:
  max_connections: 5
  
analytics:
  event_buffer_size: 1000
  
observability:
  log_level: "debug"
  enable_tracing: true
# config/development.yaml
database:
  max_connections: 5
  min_connections: 2
  pool_timeout: 10
  ssl_mode: "disable"