# config/production.yaml
app:
  environment: "production"
  
database:
  max_connections: 20
  
analytics:
  event_buffer_size: 50000
  
security:
  allowed_hosts: "security.yourdomain.com"
  
observability:
  log_level: "info"
  enable_tracing: true
# config/production.yaml
database:
  max_connections: 20
  min_connections: 10
  pool_timeout: 30
  ssl_mode: "require"
  failover_timeout: 10
  read_replicas: "postgres-replica1:5432,postgres-replica2:5432"