# config/services.yaml
services:
  database:
    name: "postgres"
    port: 5432
    health_check:
      path: "/health"
      interval: 10
      timeout: 5
      retries: 3
    connection_pool:
      max_connections: 20
      min_connections: 5
      
  cache:
    name: "redis"
    port: 6379
    health_check:
      command: "PING"
      interval: 10
      timeout: 3
      retries: 3
      
  application:
    name: "security-monitoring"
    ports:
      graphql: 8000
      websocket: 8001
      metrics: 9090
    health_check:
      path: "/health"
      interval: 30
      timeout: 10
      retries: 3
      
  monitoring:
    prometheus:
      name: "prometheus"
      port: 9091
      path: "/metrics"
    grafana:
      name: "grafana"
      port: 3000
    jaeger:
      name: "jaeger"
      ports:
        ui: 16686
        collector: 14268
        agent: 6831

networks:
  frontend:
    name: "security-frontend"
    services: ["application"]
  backend:
    name: "security-backend"
    services: ["database", "cache", "application"]
  monitoring:
    name: "security-monitoring"
    services: ["application", "monitoring.*"]